### PR TITLE
Fix visible focus and keyboard navigation in accordance with WCAG

### PR DESCRIPTION
**Pull request by podliashanyk**
Following requirements are satisfied:

- WCAG 2.0 - 2.4.7
- WCAG 2.0 - 2.1.1
- WCAG 2.0 - 2.1.2
- WCAG 2.0 - 2.4.3
- WCAG 2.1 - 1.4.11

In other words:

- All links and buttons are highlighted with at least 3:1 contrast against background when in focus
- Exception - embedded YT video where browser default is sufficient
- All functionality gains focus
- All functionality can be operated via keyboard
- Combination _hover_ + _focus_ works as expected (combo hover with mouse plus focus with keyboard)
- No keyboard traps (all elements are excitable via keyboard)
- Tab order is logical and corresponds to the visual order of elements

To test: hover over all buttons and links on the page, and Tab-traverse the whole page (both in full view and mobile view).

### CODE REVIEW

**Review by lunkwill42 — COMMENTED** [review]
This is a fine effort - but I cannot see the effect of this in Firefox - only in Chrome. Is this a known problem?

**Comment by podliashanyk** [comment]
> This is a fine effort - but I cannot see the effect of this in Firefox - only in Chrome. Is this a known problem?

@lunkwill42 Anything specific that is not reflected in the Firefox, or are there no changes whatsoever? I have tested in several browsers, including Firefox, and the changes were reflected there so this is peculiar. There are browser defaults (which I decided to not switch off as a safe fallback in some niche versions of the browsers) in addition to the changes made in this PR, but changes should be there regardless. What version of the Firefox did you use for testing?

**Comment by lunkwill42** [comment]
> > This is a fine effort - but I cannot see the effect of this in Firefox - only in Chrome. Is this a known problem?
> 
> @lunkwill42 Anything specific that is not reflected in the Firefox, or are there no changes whatsoever? I have tested in several browsers, including Firefox, and the changes were reflected there so this is peculiar. There are browser defaults (which I decided to not switch off as a safe fallback in some niche versions of the browsers) in addition to the changes made in this PR, but changes should be there regardless. What version of the Firefox did you use for testing?

Let me be more specific, @podliashanyk: I'm not entirely sure I discovered every visible change you made. 

What I did try was *tab navigation*. This apparently does move the focus around in Firefox 108.0.2, but the only visible feedback seems to be that the page scrolls down to the focus point - there is no visual feedback that shows me *which* links/buttons have been activated by tabbing.

When testing the same tab-fest in Chrome, I get a very visual feedback for every activated link.

**Comment by podliashanyk** [comment]
> > > This is a fine effort - but I cannot see the effect of this in Firefox - only in Chrome. Is this a known problem?
> > 
> > 
> > @lunkwill42 Anything specific that is not reflected in the Firefox, or are there no changes whatsoever? I have tested in several browsers, including Firefox, and the changes were reflected there so this is peculiar. There are browser defaults (which I decided to not switch off as a safe fallback in some niche versions of the browsers) in addition to the changes made in this PR, but changes should be there regardless. What version of the Firefox did you use for testing?
> 
> Let me be more specific, @podliashanyk: I'm not entirely sure I discovered every visible change you made.
> 
> What I did try was _tab navigation_. This apparently does move the focus around in Firefox 108.0.2, but the only visible feedback seems to be that the page scrolls down to the focus point - there is no visual feedback that shows me _which_ links/buttons have been activated by tabbing.
> 
> When testing the same tab-fest in Chrome, I get a very visual feedback for every activated link.

@lunkwill42  Right, I remember now that I had to make some fixes before keyboard navigation worked for me in Firefox. This is apparently a known firefox-on-mac problem.

Two guides to follow here:

- Fixes in Firefox: https://support.mozilla.org/en-US/questions/1278793
- Fixes on Mac: https://www.a11yproject.com/posts/macos-browser-keyboard-navigation/

**Comment by lunkwill42** [comment]
> Right, I remember now that I had to make some fixes before keyboard navigation worked for me in Firefox. This is apparently a known firefox-on-mac problem.

Grumble... I did turn this on ages ago in MacOS, but it seems some upgrade has turned it off again. Never realized it also affected pages rendered in Firefox (but then again, I use Vimium, so I rarely use tab to navigate web pages)  :-P

Works much better now, thanks!

**Review by lunkwill42 — APPROVED** [review]
👍

**Pull request merged**
